### ISSUE TITLE
Language file not wok.

### ISSUE THREAD

**Issue by peter58228** [benbalter/wp-document-revisions#102]
wp-document-revisions: 3.0.1
wordpress: 4.8.2
php: 7.1

MO language file not woking inside plugin's folder, but inside wp-content\languages\plugins is fine.

**Comment by NeilWJames** [comment]
I can confirm that this problem exists.
I have a copy of version 2.2 of the plugin. This had function i18n in wp-document-revisions.php. 
Version 3.0.1 has it in /includes/class-wp-document-revisions.php.
So it is looking for languages under the includes sub-directory.
#108 addresses this.
Adding a dirname moves it up to the correct level.
I also saw that WP documentation states that this should be called at "plugins-loaded", rather than init.

**Comment by benbalter** [comment]
Fixed via #108.
