### ISSUE TITLE
Unable to Upload Document

### ISSUE THREAD

**Issue by mikeblitstein** [benbalter/wp-document-revisions#114]
I can no longer upload documents or revise existing documents, as the word "Documents" is no longer on the left side of the dashboard.

**Comment by vihangm** [comment]
This has something to do with the capabilities.
Commenting https://github.com/benbalter/wp-document-revisions/blob/v3.0.0/includes/class-wp-document-revisions.php#L176 and letting it default to post edit scopes seems to fix the problem.

**Comment by NeilWJames** [comment]
@mikeblitstein 
Can you check that you have at least one xxx_documents capability available to you - particularly edit_documents. Depending on the specific document status, you may need other capabilities.

Certainly with no documents capabilities defined, the menu item does not appear. Adding any one seems to get it to appear.

**Comment by vihangm** [comment]
@NeilWJames yes we had all xxx_documents capabilities available (through the administrator role).

**Comment by NeilWJames** [comment]
Not sure that I can help you further.

You didn't say which version you have installed. So I downloaded version 
3.1.1 to ensure that I had the current released version.

For the previous couple of months we had essentially that version 
installed and did not experience your issue.

I have basically 2 users on this site available to me though there are 
others that use the system and reported no issue. They have been 
uploading documents successfully.

1. Admin user. Has all xxx_document capabilities.

Menu item appears. All documents gives some 250 documents (i.e. all of 
them).

2. Member user. Has only edit_documents and read_documents capability.

This uses a custom role - and capabilities defined using a plugin for 
our requirements.

Menu item appears. Only a couple of documents appear.

Those written by me, but now published - can only view them (as the user 
doesn't have edit_published_documents).
Can enter new documents (in pending status).

That is, it works as expected.

Also clicking on documents within a document widget, I am able to view 
the various documents (due to default read/read_documents capability). 
Clearly I cannot edit them.

As I said, on removing the edit_documents capability, the menu item no 
longer appeared.

As before, I could access the various documents via the document widget.

Good luck,
Neil
