### ISSUE TITLE
doing_it_wrong error logged

### ISSUE THREAD

**Issue by marriotb** [benbalter/wp-document-revisions#124]
The Wordpress debug.log is getting entries of the form:
`PHP Notice:  is_feed was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in /var/www/wp/wp-includes/functions.php on line 4147`

Extracting a stack trace points to wp-document-revisions as the culprit (or, at least the most recent entry in the stack).

I see several log entries for each page that is rendered. Here are two different traces as examples:
`Kint::trace() Debug Backtrace (18)
⇄→<ROOT>/wp/wp-includes/functions.php:4160 Kint::trace($trace = null)
⇄→<ROOT>/wp/wp-includes/query.php:357 _doing_it_wrong($function, $message, $version)
⇄→<ROOT>/wp/wp-content/plugins/wp-document-revisions/includes/class-wp-document-revisions.php:1181 is_feed($feeds = '')
⇄→<ROOT>/wp/wp-content/plugins/wp-document-revisions/includes/class-wp-document-revisions.php:1081 WP_Document_Revisions->verify_post_type($documentish = false)
⇄→PHP internal call WP_Document_Revisions->document_upload_dir_filter($dir)
⇄→<ROOT>/wp/wp-includes/class-wp-hook.php:286 call_user_func_array($function_name, $parameters)
⇄→<ROOT>/wp/wp-includes/plugin.php:203 WP_Hook->apply_filters($value, $args)
⇄→<ROOT>/wp/wp-includes/functions.php:1888 apply_filters($tag, $value)
⇄→<ROOT>/wp/wp-content/plugins/cherry-plugin/cherry-plugin.php:20 wp_upload_dir($time = null, $create_dir = true, $refresh_cache = false)
⇄→PHP internal call cherry_plugin_settings()
⇄→<ROOT>/wp/wp-includes/class-wp-hook.php:286 call_user_func_array($function_name, $parameters)
⇄→<ROOT>/wp/wp-includes/class-wp-hook.php:310 WP_Hook->apply_filters($value, $args)
⇄→<ROOT>/wp/wp-includes/plugin.php:453 WP_Hook->do_action($args)
⇄→<ROOT>/wp/wp-settings.php:336 do_action($tag, $arg = '')
⇄→<ROOT>/wp/wp-config.php:106 require_once()
⇄→<ROOT>/wp/wp-load.php:37 require_once()
⇄→<ROOT>/wp/wp-blog-header.php:13 require_once()
⇄→<ROOT>/wp/index.php:17 require()
`
and
`Kint::trace() Debug Backtrace (17)
⇄→<ROOT>/wp/wp-includes/functions.php:4160 Kint::trace($trace = null)
⇄→<ROOT>/wp/wp-includes/query.php:357 _doing_it_wrong($function, $message, $version)
⇄→<ROOT>/wp/wp-content/plugins/wp-document-revisions/includes/class-wp-document-revisions.php:1181 is_feed($feeds = '')
⇄→<ROOT>/wp/wp-content/plugins/wp-document-revisions/includes/class-wp-document-revisions.php:1081 WP_Document_Revisions->verify_post_type($documentish = false)
⇄→PHP internal call WP_Document_Revisions->document_upload_dir_filter($dir)
⇄→<ROOT>/wp/wp-includes/class-wp-hook.php:286 call_user_func_array($function_name, $parameters)
⇄→<ROOT>/wp/wp-includes/plugin.php:203 WP_Hook->apply_filters($value, $args)
⇄→<ROOT>/wp/wp-includes/functions.php:1888 apply_filters($tag, $value)
⇄→<ROOT>/wp/wp-content/plugins/wp-security-audit-log/classes/SensorManager.php:47 wp_upload_dir($time = null, $create_dir = true, $refresh_cache = false)
⇄→<ROOT>/wp/wp-content/plugins/wp-security-audit-log/wp-security-audit-log.php:192 WSAL_SensorManager->__construct(WpSecurityAuditLog $plugin)
⇄→<ROOT>/wp/wp-content/plugins/wp-security-audit-log/wp-security-audit-log.php:158 WpSecurityAuditLog->__construct()
⇄→<ROOT>/wp/wp-content/plugins/wp-security-audit-log/wp-security-audit-log.php:1152 WpSecurityAuditLog::GetInstance()
⇄→<ROOT>/wp/wp-settings.php:314 include_once()
⇄→<ROOT>/wp/wp-config.php:106 require_once()
⇄→<ROOT>/wp/wp-load.php:37 require_once()
⇄→<ROOT>/wp/wp-blog-header.php:13 require_once()
⇄→<ROOT>/wp/index.php:17 require()`

Regards
Brian

**Comment by NeilWJames** [comment]
The line (includes/class-wp-document-revisions.php:1181) invoking is_feed() is 
if ( is_feed() && 'document' === $wp_query->query_vars['post_type'] ) {

This is functionally equivalent to
if ( 'document' === $wp_query->query_vars['post_type'] && is_feed() ) {

However this construction would have the advantage that due to short-circuit evaluation is_feed() is not called unless there is a query result.

According to the codex Conditional_Tags page in this case a call to is_feed() is valid.

@marriotb,
Would it be possible to modify this line as above and see whether the errors persist please?

Note. Sorry, I have no idea whether the underlying code is correct or not.

**Comment by marriotb** [comment]
Hi @NeilWJames 
I tried what you suggested, but it failed, because the $wp_query object is not always set up. 
Presumably it is normally set up after the query is run, so it doesn't matter which of the two tests is performed first as they both fail.

What I did do that seems to work is to test for a valid $wp_query first, like so:
`if ( (! is_null($wp_query)) && is_feed() && 'document' === $wp_query->query_vars['post_type'] ) {
`

This removes the error reporting from the log file, but I haven't been able to produce a positive test case: one in which all three of the conditions are satisfied. I don't understand the underlying context well enough to trigger a query for a document that is a feed (RSS or similar).

I'll leave that to the plug-in maintainers:-)

Regards
Brian

**Comment by tbnv** [comment]
Was a fix pushed to the WordPress extensions repo? Today I noticed this error on a website using WordPress `4.9.7` and WP Document Revisions `3.1.2`.

**Comment by NeilWJames** [comment]
There is a fix in this Github repository - lines 1195/1196 of /includes/class-wp-document-revisions.php

This has not yet been bundled into a release in the plugins repository.

This fix may not be sufficient as wp_query itself may be empty, but I am currently blocked on my fork copy due to a problem in the feed (!) where my version generates an empty feed - which then fails one of the tests as it should provide no feed. [This test also logically fails with the plugin version and WP 4.9.7 when entering http://site/documents/feed/ as some XML is returned.]

Also for information, the WP coding standards have evolved - so any update to the current version would give a number of phpcs errors to correct/workaround.

So you might like to manually edit your version to get temporary relief. 

Hope this is of use,
Neil James
