### ISSUE TITLE
404 errors when trying to view files

### ISSUE THREAD

**Issue by aaronhb** [benbalter/wp-document-revisions#159]
I have checked the closed issues regarding this and tried fixes from 119 ect. but no matter what I do all documents show a 404. I am not sure what to do. I am hosted on WPEngine but am unable to figure out why the links do not work. I have installed the latest version and have the newest WP. This is not a multi install or shared. Any help is greatly appreciated!

**Comment by aaronhb** [comment]
I think i see the issue. After digging deeper it appears the url provided is missing the / at the end. I have it set in the permalinks settings but for the document url it seems to be stopping after the extension .pdf, .txt, .docx, etc..

The following works if you add a / at the end

http://spg-i.com/documents/2019/04/test.pdf

so new code would force a trailing / for permalinks like so

http://spg-i.com/documents/2019/04/test.pdf/

Does it have to have the file extension in the URL as that might cause issues with the linking.

**Comment by aaronhb** [comment]
in the class-wp-document-revisions.php I changed line 621 from...

$link = apply_filters( 'document_permalink', $link, $document ) ;

to

$link = apply_filters( 'document_permalink', $link, $document ) . '/';

and it seems to have fixed my problem of no trailing / causing the links to not work.

Is this the best way to do this or do you have another way and can you include in the next build so I do not get my changes overwritten?

**Comment by NeilWJames** [comment]
I have looked at this a little overnight.

FWIW, on my site, there is no trailing slash in the permalink - and it finds the document OK. However, adding one (as you have done) also finds it. Other people have reported a similar problem.

I am currently unable to answer why the issue is occurring at all as I don't have the issue.

But to answer your question - how to make it so that you do not edit the underlying plugin.

The way to not touch the plugin is to use the capability that is on the line you entered - apply_filters.

The easiest is to create a file in /wp_content/mu-plugins called document_permalink.php and put this in it:
```
<?php

/**
 * Ensure that WPDR permalink has a trailing slash if installation has one.
 *
 * @param string $link URL to redirect to.
 * @param string $document post object.
 * @return string
 */
if ( ! function_exists('wpdr_document_permalink')) {

	function wpdr_document_permalink( $link, $document ) {

		return user_trailingslashit( $link );
	}

	add_filter( 'document_permalink', 'wpdr_document_permalink', 10, 2 );
}
?>

```
This will add the trailing slash IF that is what you have defined your permalink structure to have.

Mine is set to `/%year%/%monthnum%/%postname%/` that is it has a trailing / and on implementing this, it adds the trailing slash - which also retrieves the document.

You can see your value by going to Setting -> Permalinks and looking at what is set in Custom Structure (even if it is the one not selected).

If you implement this, you will need to remove the one you have added since there would then be two.

If a plugin fix is forthcoming that adds the trailing slash, then this code does not add a second.

Hope this helps,
Neil

**Comment by benbalter** [comment]
@aaronhb are you able to share the contents of your `.htaccess` file?
