### ISSUE TITLE
Revisions logs only show one revision

### ISSUE THREAD

**Issue by aaronhb** [benbalter/wp-document-revisions#160]
When adding a document and them uploading a revision or document it shill only shows one revision and only updates the notes for the one rather than a revision for each time i modify the document.

**Comment by NeilWJames** [comment]
This is the expected outcome IF
a) You are using any version of the released plugin (i.e. you did not download the plugin from Github here since February); and
b) You have the standard revision creation process turned off, by setting (normally in the configuration file)
`define('WP_POST_REVISIONS', false);`
or possibly setting it to 1.

Since the basis of this plugin is that there are revisions, I made a fix #140, which Ben accepted, that normally sets the number of revisions to unlimited for document post types even if the value is set off globally. This has not yet been released.

Please could you check if this is the case.

Thanks,
Neil

**Comment by benbalter** [comment]
Published [v3.2.2](https://github.com/benbalter/wp-document-revisions/releases/tag/3.2.2) off of the `master` branch here.

**Comment by aaronhb** [comment]
This does not appear to be fixed as I have updated to the latest version 3.2.2 just now and still links do not work. 

I have tried changing the media settings but nothing seems to work.

Here is a link to document I have added and shows as added in admin but links do not work for permalinks.

http://spg-i.com/documents/2019/04/test.pdf

I noticed the files being uploaded are actually being renamed to long strings like so 14820c7746e7f4fb9416d179285ebcff

In the admin in media I do not see any of the documents showing. If i delete the plugin the documents with the long string name then show. 

Any help would be greatly appreciated. :)

**Comment by aaronhb** [comment]
I think i see the issue. After digging deeper it appears the url provided is missing the / at the end. I have it set in the permalinks settings but for the document url it seems to be stopping after the extension .pdf, .txt, .docx, etc.. 

The following works if you add a / at the end

http://spg-i.com/documents/2019/04/test.pdf

so new code would force a trailing / for permalinks like so

http://spg-i.com/documents/2019/04/test.pdf/

Does it have to have the file extension in the URL as that might cause issues with the linking.

**Comment by aaronhb** [comment]
in the class-wp-document-revisions.php I changed line 621 from...

$link = apply_filters( 'document_permalink', $link, $document ) ;

to 

$link = apply_filters( 'document_permalink', $link, $document ) . '/';

and it seems to have fixed my problem of no trailing / causing the links to not work.

Is this the best way to do this or do you have another way and can you include in the next build so I do not get my changes overwritten?

**Comment by NeilWJames** [comment]
@aaronhb 
The comments above refer to the problem you have raised in #159.

Can you confirm whether you are still finding that no revisions are being createdwith V3.2.2 please?
