### ISSUE TITLE
Offload documents to cloud services

### ISSUE THREAD

**Issue by davidzuluaga5** [benbalter/wp-document-revisions#184]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

The problem comes up when the document use more disk space and the server runs out of it. So I want to be able to offload this to cloud services like s3, google storage, etc.
WP document revisions is an amazing plugin and has a huge potential, so I am heavily using it for huge repositories, but I've come up with the problem of server capacity.

### Describe the solution you'd like

I'd like to plugin to be able to offload the files to a cloud service, but keep it secure under the wordpress access permissions system.

### Describe alternatives you've considered

The closest I've come to is using media cloud and statless plugin:
https://es.wordpress.org/plugins/ilab-media-tools/
https://es.wordpress.org/plugins/wp-stateless/

They both work as a plugin to offload the server and save the files directly to cloud services.

**The issue** is that the links become **publicly available**, so any security is bypassed.

I'd like to hear any approach to avoid server disk size limitations, while keeping it secure!

Thanks for your help!!!

**Comment by NeilWJames** [comment]
@davidzuluaga5,
I would like to help, but I do not use a cloud service (and would not sign up to a paying service just to see what happens).

Can you explain what is happening when you use either of these plugins with WP Document Revisions and where the security issues arise.

Clearly in any reply, I don't need to know the actual name of either WP_Server or Cloud_Server, so you can change them to one or other above.

I possibly think that I know what the problem is, but would like the most complete description since I am only doing thought experiments on what problem you could be having.

Thanks,
Neil James

**Comment by davidzuluaga5** [comment]
Hi Neil! many thanks.

It is not a problem of the plugin itself and I am sorry if that's the impression.

The plugin works like a charm and do not intent to make any change in the plugin end. What I encounter is a limit when trying to use a cloud service for storage. For the plugins that store objects in AWS, Google cloud, etc, they need to store it publicly so the server can retrieve them.

I might have found a solution, and is regarding the "avoid hotlinking" procedure available in S3 (I guess other storage services have it too). It consists in telling the storage services that the objects can only be accessed from the server IP only, so WP can connect and load them. However, if the user tries to access the object stored (document, etc) by directly copying/pasting the URL, he won't be able to do so. So that would solve the problem.

I case you wonder why not use the usual storage of cloud services, just in terms of costs, the storage services as S3 are a fraction f the cost of the traditional storage, so for big repositories it has a huge impact in costs.
For example 1 terabyte in S3 is around 25 USD (Another storage tiers are actually 10 USD), and for the typical sage (EBS) is 100 USD.
These costs are monthly.

This is a tutorial for the mentioned procedure: https://www.cloudberrylab.com/resources/blog/how-to-prevent-hotlinking-of-imaged-hosted-on-amazon-s3/

Let

**Comment by davidzuluaga5** [comment]
Solution found.

**Comment by NeilWJames** [comment]
@davidzuluaga5 
Glad that you have found a solution. I agree that the security issue would be related to these services allowing a directory scan. The plugin normally relies on standard WP processing not allowing a directory scan and creating an encoded file name.

Using a cloud service and granting directory scan access will give rise to a security hole.

Thus the document library should be kept in a different directory to the nomal media directory since this one is generally configured to take advantage of CDN capabilities.

However it is worthwhile to point out that the plugin creates the  download file using the PHP function readfile which implies that the file is local. So although Cloud Services can be used to hold the file, it does currently need to be held locally as well.

This can be addressed by two actions:
a) Use of WP_Filesystem (using "direct") instead of readfile.
b) Creation of another plugin that will do the manipulation of the access method for the document library and to invoke cloud services.

Then the documents can be held on a cloud service (where only the server should have access).

Note that in this configuration when serving the file, it needs to download the file from the cloud and then from the server to the client with likely an increased reponse time seen. This may, or may not be, acceptable, but does need to be taken into consideration.

Hope this is of use,
Neil James
