### ISSUE TITLE
How create template page for document?

### ISSUE THREAD

**Issue by aiiddqd** [benbalter/wp-document-revisions#45]
I need to make a page of the document, similar to the page file in the Media.
But standard mechanism redirect URL to file and starting download.

How can I get solutions like Google drive?
1. default URL to file page (preview, create version, history ...) on front end
2. URL to file - separately. 

Get two scenario:
1. open page, preview, history, create version...
2. or direct download, without preview etc.

**Comment by EmmaBritnor** [comment]
Hey Ben,

Just checking in on this ticket to see if anything may have developed since 2014? I have specific requirements from a client to have a post page which contains the title, excerpt and a button which is linked with the URL to the current document version (attainable with get_permalink()). 

I am aware my request is slightly different to uptimizt, I am sure it's probably something I am missing, but if you could point me in the right direction that would be great! If you could let me know how I could achieve this with my own custom theme, I have noticed that you have specific redirect rules written in place, is there a way I could customise these to enable each document to have a post page instead of the specific URL to the downloadable document?

Thanks,
Emma
